setting:
  - module: ml.DataLoader
    option:
      - optimize_sliceable_dataset: true
  - module: ROOT
    option:
      - friend_allow_missing: false
  - module: cms.CollisionData
    option:
      - eras:
          2022_preEE: [B, C, D]
          2022_EE: [E, F, G]
          2023_preBPix: [C01, C02, C11, C12, C3, C4]
          2023_BPix: [D1, D2]
  - module: HCR.InputBranch
    option:
      - feature_ancillary: [xW, nSelJets, xbW, year]
