triggers:  
  UL18:
    - PFJet500
    - AK8PFJet500 
    - PFHT1050
    - AK8PFJet360_TrimMass30
    - AK8PFJet380_TrimMass30
    - AK8PFJet400_TrimMass30
    - AK8PFHT800_TrimMass50
    - AK8PFHT750_TrimMass50
    - AK8PFJet330_PFAK8BTagCSV
  # Run3 triggers
  2022_EE: &triggers_2022
    - AK8PFJet230_SoftDropMass40
    - AK8PFJet425_SoftDropMass40
    - AK8PFJet250_SoftDropMass40_PFAK8ParticleNetBB0p35
  2022_preEE: *triggers_2022
  2023_BPix: &triggers_2023
    - AK8PFJet230_SoftDropMass40
    - AK8PFJet425_SoftDropMass40
    - AK8PFJet250_SoftDropMass40_PFAK8ParticleNetBB0p35
    - AK8PFJet230_SoftDropMass40_PFAK8ParticleNetBB0p06
  2023_preBPix: *triggers_2023
  # '2024': 
  #   - PFHT250_QuadPFJet25_PNet2BTagMean0p55
  #   - PFHT280_QuadPFJet30_PNet2BTagMean0p55