analysis_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_cutflow/test_dump_cutflow.yml

check_cutflow_Run3_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - merging_files_Run3_coffea4bees
  script:
    - pixi run snakemake output/run3_nominal/cutflow_validation_run3_nominal.txt -s coffea4bees/workflows/Snakefile_analysis.smk --configfile coffea4bees/workflows/config/nominal_run3.yml --config test=true --jobs 4
  artifacts:
    paths:
      - barista_framework/output/run3_nominal/cutflow_validation_run3_nominal.txt
      - barista_framework/output/run3_nominal/cutflow_run3_nominal.yml

analysis_cutflow_Run3_2024_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - analysis_test_Run3_2024_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-cutflow-Run3-2024.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_cutflow_Run3_2024/test_dump_cutflow.yml

analysis_mixed_cutflow_coffea4bees:  
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - analysis_test_mixed_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-mixed-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_mixed_cutflow/test_dump_cutflow_mixed_data.yml
      - output/analysis_mixed_cutflow/test_dump_cutflow_mixed_bkg.yml

skimmer_analysis_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - skimmer_analysis_test_coffea4bees
  script:
    - source coffea4bees/scripts/skimmer-analysis-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/skimmer_analysis_cutflow/test_dump_skimmer_cutflow.yml

analysis_systematics_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - analysis_systematics_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-systematics-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_systematics_cutflow/test_dump_systematics_cutflow.yml

analysis_unsup_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - job: analysis_unsup_test_coffea4bees
      optional: true
  script:
    - source coffea4bees/scripts/analysis-unsup-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_unsup_cutflow/test_dump_cutflow_job_unsup.yml

synthetic_dataset_analyze_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - synthetic_dataset_analyze_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_cutflow/test_dump_cutflow_synthetic_datasets.yml

synthetic_dataset_analyze_cutflow_Run3_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - synthetic_dataset_analyze_Run3_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-cutflow-Run3.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_cutflow_Run3/test_dump_cutflow_synthetic_datasets.yml


weights_trigger_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - weights_trigger_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/weights-trigger-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/weights_trigger_cutflow/test_dump_cutflow_trigWeight.yml

SvB_friendtree_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - SvB_friendtree_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/SvB-friendtree-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/SvB_friendtree_cutflow/test_dump_cutflow_SvB_friend.yml

analysis_dilepttbar_cutflow_coffea4bees: 
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - analysis_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-dilepttbar-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_dilepttbar_cutflow/test_dump_cutflow.yml

mixeddata_analyze_cutflow_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - mixeddata_analyze_coffea4bees
  script:
    - source coffea4bees/scripts/mixeddata-analyze-cutflow.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output//mixeddata_analyze_cutflow/test_dump_cutflow_mixeddata.yml

check_cutflow_lowpt_Run2_coffea4bees:
  stage: cutflow
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - merging_files_lowpt_Run2_coffea4bees
  script:
    - pixi run snakemake output/run2_lowpt/cutflow_validation_run2_lowpt.txt -s coffea4bees/workflows/Snakefile_analysis.smk --configfile coffea4bees/workflows/config/lowpt_run2.yml --config test=true --jobs 4
  artifacts:
    paths:
      - barista_framework/output/run2_lowpt/cutflow_validation_run2_lowpt.txt
      - barista_framework/output/run2_lowpt/cutflow_run2_lowpt.yml
