generate_dataset_coffea4bees:
  stage: classifier
  extends: .base_analysis_coffea4bees
  script:
    - python -c "from pathlib import Path; print('resolved:', Path('coffea4bees').resolve(strict=True))"
    - python -c "from src.classifier.config.state import Extensions; print('extensions:', Extensions.get_extensions())"
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/generate_dataset.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - output/dataset/sparse.root
      - output/dataset/dense.root

cache_coffea4bees:
  stage: classifier
  extends: .base_analysis_coffea4bees
  needs:
    - generate_dataset_coffea4bees
  script:
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_cache.yml ${CLASSIFIER_WFS}/common.yml
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_cache_compare.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - output/main_cache/diagnostics/logs.html

train_coffea4bees:
  stage: classifier
  extends: .base_analysis_coffea4bees
  needs:
    - generate_dataset_coffea4bees
  script:
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_train.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - output/main_train/result.json
      - output/main_train/states.pkl
      - output/main_train/model_test-SvD__*.pkl
      - output/main_train/diagnostics/logs.html
      - output/main_train/report/

evaluate_coffea4bees:
  stage: classifier
  extends: .base_analysis_coffea4bees
  needs:
    - generate_dataset_coffea4bees
    - train_coffea4bees
  script:
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_evaluate.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - output/main_evaluate/diagnostics/logs.html
      - output/main_evaluate/chunks/*.root