reana-job:
  stage: reana
  extends:
    - .base_analysis
  tags:
    - k8s-cvmfs
  script:
    - ./run_container snakemake -h
    - pixi run bash -c "source coffea4bees/scripts/reana-job.sh $NAME"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      variables:
        NAME: "coffea4bees_scheduled_${CI_COMMIT_SHORT_SHA}"
    - if: $RUN_REANA == "true"
      variables:
        NAME: "coffea4bees_manual_${CI_COMMIT_SHORT_SHA}"
    - if: $CI_PIPELINE_SOURCE == "push"
      when: never
  allow_failure: true
