tools_merge_test_coffea4bees:
  stage: tools
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - analysis_test_coffea4bees
    - analysis_signals_test_coffea4bees
  script:
    - source coffea4bees/scripts/tools-merge-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/tools_merge_test/test.coffea

tools_memory_test_coffea4bees:
  stage: tools
  needs:
    - setup_coffea4bees
    - analysis_systematics_test_coffea4bees
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/tools-memory-test.sh
  allow_failure: true
  artifacts:
    paths:
      - output/tools_memory_test/mprofile_ci_test.png

tools_make_jcm_weights_coffea4bees:    
  stage: tools
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/tools-make-jcm-weights.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/tools_make_jcm_weights/testJCM_ROOT/jetCombinatoricModel_SB_.yml

tools_twostageclosure_mixed_coffea4bees:
  stage: tools
  extends:
    - .base_combine_coffea4bees
  needs: 
    - setup_coffea4bees
    - analysis_test_mixed_coffea4bees
  script:
    - source coffea4bees/scripts/tools-twostageclosure-mixed.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/tools_twostageclosure_mixed/test_dump_twoStageClosureInputsCounts.yml

tools_perf_profile_coffea4bees:
  stage: tools
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
  script:
    - source coffea4bees/scripts/tools-perf-profile.sh --output-base /builds/$CI_PROJECT_PATH/output
  allow_failure: true
  artifacts:
    paths:
      - output/perf_profile/perf_profile.txt
      - output/perf_profile/perf_profile.csv

merging_files_lowpt_Run2_coffea4bees:
  stage: tools
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - analysis_data_lowpt_Run2_coffea4bees
    - analysis_MC_lowpt_Run2_coffea4bees
  script:
    - pixi run snakemake output/run2_lowpt/histAll_run2_lowpt.coffea -s coffea4bees/workflows/Snakefile_analysis.smk --configfile coffea4bees/workflows/config/lowpt_run2.yml --config test=true --jobs 4
  artifacts:
    paths:
      - barista_framework/output/run2_lowpt/histAll_run2_lowpt.coffea

merging_files_Run3_coffea4bees:
  stage: tools
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - analysis_data_Run3_coffea4bees
    - analysis_MC_Run3_coffea4bees
  script:
    - pixi run snakemake output/run3_nominal/histAll_run3_nominal.coffea -s coffea4bees/workflows/Snakefile_analysis.smk --configfile coffea4bees/workflows/config/nominal_run3.yml --config test=true --jobs 4
  artifacts:
    paths:
      - barista_framework/output/run3_nominal/histAll_run3_nominal.coffea
