analysis_plot_coffea4bees:    
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_plot/RunII/

analysis_unsup_plot_coffea4bees:
  stage: plot 
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - analysis_unsup_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-unsup-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_unsup_plot/RunII/

# analysis_truthStudy_plot_coffea4bees:
#   stage: plot 
#   extends:
#     - .base_analysis
#   needs: 
#     - setup_workspace
#     - analysis_truthStudy_test_coffea4bees
#   script:
#     - source coffea4bees/scripts/analysis-truthStudy-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
#   artifacts:
#     paths:
#       - output/analysis_truthStudy_plot/

analysis_iplot_coffea4bees:
  stage: plot 
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-iplot.sh --output-base /builds/$CI_PROJECT_PATH/output

code_plot_test_coffea4bees:
  stage: plot
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - tools_merge_test_coffea4bees
  script:
    - source coffea4bees/scripts/code-plot-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/code_plot_test/test_dumpPlotCounts.yml

synthetic_dataset_plot_coffea4bees:
  stage: plot
  extends:
    - .base_analysis
  needs: 
    - setup_workspace
    - synthetic_dataset_cluster_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-plot.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_plot/jet-splitting-PDFs-test/

mixeddata_study_hemispheres_coffea4bees:
  stage: plot
  extends:
    - .base_analysis
  needs:
    - setup_workspace
    - mixeddata_cluster_coffea4bees
  script:
    - source coffea4bees/scripts/mixeddata-study-hemispheres.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/test_study_hemispheres/hemi_statistics_UL18.yml