include:
  - local: workflows/gitlab-CI/stages_code.yml
  # - local: workflows/gitlab-CI/stages_classifier.yml
  - local: workflows/gitlab-CI/stages_skimmer.yml
  - local: workflows/gitlab-CI/stages_friendtree.yml
  - local: workflows/gitlab-CI/stages_analysis.yml
  - local: workflows/gitlab-CI/stages_tools.yml
  - local: workflows/gitlab-CI/stages_plots.yml
  - local: workflows/gitlab-CI/stages_cutflow.yml
