analysis_test_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test/test_databkgs.coffea

analysis_signals_test_coffea4bees:
  stage: analysis
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-signals-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_signals_test/test_signal.coffea

analysis_test_Run3_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test-Run3.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_Run3/test.coffea

analysis_test_Run3_2024_coffea4bees:
  stage: analysis
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test-Run3-2024.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/analysis_test_Run3_2024/test.coffea

analysis_truthStudy_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-truthStudy-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_truthStudy_test/testTruth.coffea


synthetic_dataset_cluster_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-cluster.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/synthetic_dataset_cluster/test_synthetic_datasets.coffea

mixeddata_cluster_coffea4bees:
  stage: analysis
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/mixeddata-cluster.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/mixeddata_cluster/test_mixed_datasets.coffea
      - output/mixeddata_cluster/data_UL18C/hemisphereLib_27c58f3a-05bd-11ee-b80a-3ebde183beef_0_1002.root
      - output/mixeddata_cluster/data_UL18D/hemisphereLib_e850b3fc-05bc-11ee-a472-0ebce183beef_0_1000.root
      - output/mixeddata_cluster/data_UL18A/hemisphereLib_109efe9a-05bd-11ee-a1fc-9ebde183beef_0_1001.root
      - output/mixeddata_cluster/data_UL18B/hemisphereLib_eb8f6c84-05bc-11ee-affb-c7bce183beef_0_1000.root

analysis_unsup_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-unsup-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_unsup_test/test_unsup.coffea

analysis_test_mixed_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test-mixed.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_mixed/testMixedBkg_TT.coffea
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed.coffea
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed_kfold.coffea
      - output/analysis_test_mixed/testMixedData.coffea
      - output/analysis_test_mixed/testMixedBkg_TT.json
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed.json
      - output/analysis_test_mixed/testMixedBkg_data_3b_for_mixed_kfold.json      
      - output/analysis_test_mixed/testMixedData.json
      - output/analysis_test_mixed/testSignal_preUL.coffea
      - output/analysis_test_mixed/testSignal_preUL.json
      - output/analysis_test_mixed/testSignal_UL.coffea
      - output/analysis_test_mixed/testSignal_UL.json

analysis_systematics_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-systematics-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_systematics_test/test_systematics.coffea

skimmer_analysis_test_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs: 
    - setup_coffea4bees
    - skimmer_test_coffea4bees
  script:
    - source coffea4bees/scripts/skimmer-analysis-test.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/skimmer_analysis_test/test_skimmer.coffea

synthetic_dataset_analyze_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - synthetic_dataset_make_dataset_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_analyze/test_synthetic_datasets.coffea

synthetic_dataset_analyze_Run3_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - synthetic_dataset_make_dataset_Run3_coffea4bees
  script:
    - source coffea4bees/scripts/synthetic-dataset-analyze-Run3.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/synthetic_dataset_analyze_Run3/test_synthetic_datasets.coffea


weights_trigger_analysis_coffea4bees:   
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - weights_trigger_friendtree_coffea4bees
  script:
    - source coffea4bees/scripts/weights-trigger-analysis.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/weights_trigger_analysis/test_trigWeight.coffea

SvB_friendtree_analysis_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - SvB_friendtree_coffea4bees
  script:
    - source coffea4bees/scripts/SvB-friendtree-analysis.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/SvB_friendtree_analysis/test_SvB_friend.coffea

mixeddata_analyze_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  needs:
    - setup_coffea4bees
    - mixeddata_split_dataset_coffea4bees
  script:
    - source coffea4bees/scripts/mixeddata-analyze.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts:
    paths:
      - output/mixeddata_analyze/test_mixeddata.coffea

analysis_test_lowpt_data_Run2_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test-lowpt-data-Run2.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_lowpt_data_Run2/test_data_lowpt.coffea

analysis_test_lowpt_signal_Run2_coffea4bees:
  stage: analysis   
  extends:
    - .base_analysis_coffea4bees
  script:
    - source coffea4bees/scripts/analysis-test-lowpt-signal-Run2.sh --output-base /builds/$CI_PROJECT_PATH/output
  artifacts: 
    paths:
      - output/analysis_test_lowpt_signal_Run2/test_signal_lowpt.coffea