classifier_unit_tests:
  stage: classifier
  extends: .base_classifier_coffea4bees
  script:
    - export CLASSIFIER_CONFIG_PATHS="coffea4bees"
    - python -m unittest coffea4bees.classifier.tests.test_imports
    - python -m src.classifier.test.check_configs

classifier_generate_dataset:
  stage: classifier
  extends: .base_classifier_coffea4bees
  needs:
    - setup_coffea4bees
  script:
    - export CLASSIFIER_CONFIG_PATHS="coffea4bees"
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/generate_dataset.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - barista_framework/output/dataset/sparse.root
      - barista_framework/output/dataset/dense.root

classifier_train:
  stage: classifier
  extends: .base_classifier_coffea4bees
  needs:
    - classifier_generate_dataset
  script:
    - export CLASSIFIER_CONFIG_PATHS="coffea4bees"
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_train.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - barista_framework/output/main_train/result.json
      - barista_framework/output/main_train/states.pkl
      - barista_framework/output/main_train/model_test-SvD__*.pkl

classifier_evaluate:
  stage: classifier
  extends: .base_classifier_coffea4bees
  needs:
    - classifier_train
  script:
    - export CLASSIFIER_CONFIG_PATHS="coffea4bees"
    - python -m src.classifier.task.main from ${CLASSIFIER_WFS}/main_evaluate.yml ${CLASSIFIER_WFS}/common.yml
  artifacts:
    paths:
      - barista_framework/output/main_evaluate/chunks/*.root
