data4bName: data
taglabel4b:   fourTag

data3bName: mixeddata_all
taglabel3b:   fourTag

taglabel3b_tt: threeTag

selJets: selJets_noJCM.n
tagJets: tagJets_noJCM.n

subtract3bTT: False
#threeTightTagFraction: 0.463830
float_t: true                    # mixed-data fit: derive t from data4b/(JCM·mixed_3b) normalization
