# template:
# - model: path to model
# - FvT: path to FvT friend tree

main:
  module: train
  option:
    - --max-loaders 1
    - --max-trainers 1

model:
  - module: HCR.SvB.ttHbb.baseline.Train
    option:
      - --kfold-seed SvB random
      - --kfold-seed-offsets 0
      - --architecture
      - n_features: 8
        use_kv_proj: true
        use_attention_gate: true
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384

dataset:
  - module: HCR.SvB.Background # load background dataset
    option:
      - --metadata coffea4bees/metadata/datasets/archive/Run2_2024_v2/
      - --norm 3
      - --regions SR SB
      - --JCM-weight "" coffea4bees/metadata/weights/JCM/2024_v2_nominal/jetCombinatoricModel_SB_2024_v2.yml@@JCM_weights
      - --friends "" coffea4bees/metadata/datasets/archive/Run2_2024_v2/classifier_inputs_nominal.json@@HCR_input 
      - --friends label:data {FvT}/result.json@@analysis.0.merged # setup the path to FvT friend tree

  - module: HCR.ttHbb.Signal # load ttHbb signal dataset
    option:
      - --metadata coffea4bees/metadata/datasets/archive/Run2_2024_v2/
      - --regions SR SB
      - --friends "" coffea4bees/metadata/datasets/archive/Run2_2024_v2/classifier_inputs_nominal.json@@HCR_input 

setting:
  - module: IO
    option:
      - output: "{model}"
