# coffea4bees/classifier/config/workflows/HH4b_2024_v2_lowpt/FvT/workflow_config.yml
#
# Config for src/classifier/workflow/Snakefile.
# To keep outputs from a separate run, change output_dir.

eos_base: "root://cmseos.fnal.gov//store/user/algomez/XX4b/2024_v2/lowpt_sel_LWP"
plot_base: "root://eosuser.cern.ch//eos/user/a/algomez/www/HH4b/Plots"

classifier_config_paths: coffea4bees
wfs_base: coffea4bees/classifier/config/workflows/HH4b_2024_v2_lowpt/FvT
label: lowpt_FvT
output_dir: output/{label}/
plot_inputs: true

model: "{eos_base}/classifier/{label}"
friend: "{eos_base}/friend/{label}"
train_template: "model: {eos_base}/classifier/{label}"
eval_template: "model: {eos_base}/classifier/{label}, FvT: {eos_base}/friend/{label}"
metadata: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/classifier_inputs_lowpt_wlowptJCM.json@@HCR_input_lowpt"
