label: "ttHbb_synthetic"
output_path: "output/ttHbb_synthetic/coffea_outputs/"
datasets:
  - "synthetic_data"
years:
  - "UL16_preVFP"
  - "UL16_postVFP"
  - "UL17"
  - "UL18"
dataset:
  - "synthetic_data"
datasets_file: "coffea4bees/metadata/datasets/synthetic_data.yml"
year_eras:
  UL16_preVFP: []
  UL16_postVFP: []
  UL17: []
  UL18: []

analysis_config:
  processor: "coffea4bees/analysis/processors/processor_ttHbb.py"
  dataset_location: "coffea4bees/metadata/datasets/"
  datasets_file: "coffea4bees/metadata/datasets/synthetic_data.yml"
  friend_file: "tmp/friends_synthetic.yml"
  weights_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/weights_ttHbb.yml"
  runner:
    workers: 16
    worker_memory: 8GB
    chunksize: 50000
    condor: false
    shared_dask: false
  config:
    blind: false
    apply_FvT: false
    apply_JCM: false
    apply_trigWeight: false
    apply_btagSF: true
    apply_boosted_veto: false
    run_SvB: true
    SvB_MA: true
    SvB: null
    apply_lepton_veto: false
    hist_cuts: ["pass_nSelJets_gt6", "fail_nSelJets_le6"]
    top_reconstruction: fast
    plot_ttbar_with_weights: true
