label: "ttHbb_mixeddata"
output_path: "output/ttHbb/"
dataset:
  - "mixeddata"
datasets_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/synthetic_datasets.yml"
year_eras:
  2016: []
  2017: []
  2018: []

analysis_config:
  processor: "coffea4bees/analysis/processors/processor_ttHbb.py"
  dataset_location: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/"
  datasets_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/synthetic_datasets.yml"
  friend_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/friends_ttHbb.yml"
  weights_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/weights_ttHbb.yml"
  runner:
    workers: 4
    worker_memory: 8GB
    chunksize: 10000
    condor: true
    shared_dask: true
    run_performance: true
  config:
    blind: false
    apply_FvT: true
    apply_JCM: true
    apply_trigWeight: true
    apply_btagSF: true
    apply_boosted_veto: false
    run_SvB: true
    SvB_MA: true
    SvB: null
    hist_cuts: ["pass_nSelJets_gt6", "fail_nSelJets_le6"]
    top_reconstruction: fast
    plot_ttbar_with_weights: true

additional_parameters: "--condor --shared-dask --run-performance"

plot_config_mixeddata: "coffea4bees/plots/metadata/plots_mixeddata_vs_data.yml"

convert_hist_to_json:
  histos: 
    - "SvB_MA.ps_ttHbb"
    - "SvB_MA.ps"
combine_outdir: "datacards/"
make_combine_inputs:
  stat_only: ""
  bkgsyst: "coffea4bees/stats_analysis/files/HIG-24-010/hh/hists_closure_3bDvTMix4bDvT_SvB_MA_ps_hh_rebin1.pkl"
channels:
  ttHbb_mixeddata:
    signallabel: "ttHbb"
    othersignal: ""
    variable: "SvB_MA.ps"
    signal: "ttHbb"
    closure_subdir: "hh"
    region: "sum"
    cut: "sum"
    combine_flags: "--three_tag threeTag --four_tag fourTag --region sum"
    data_process: "mixeddata"
    multijet_process: "data"
    tt_processes: ["TTTo", "TTbar4b_from_d3"]

combine_flags: "--three_tag threeTag --four_tag fourTag --region sum"

likelihood_scan_points: 40
likelihood_scan_r_min: -1
likelihood_scan_r_max: 1
likelihood_scan_y_cut: 100
likelihood_scan_y_max: 100
