label: "ttHbb"
output_path: "output/ttHbb/"
analysis_config:
  processor: "coffea4bees/analysis/processors/processor_ttHbb.py"
  dataset_location: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/"
  friend_file: "coffea4bees/metadata/datasets/archive/Run2_2024_v2/friends_HH4b.yml"
  weights_file: "coffea4bees/metadata/weights/weights_HH4b_2024_v2.yml"
  runner:
    workers: 4
    worker_memory: 8GB
    chunksize: 10000
    condor: true
    shared_dask: true
    run_performance: true
  config:
    blind: true
    apply_FvT: true
    apply_JCM: true
    apply_trigWeight: true
    apply_btagSF: true
    apply_boosted_veto: false
    run_SvB: true
    SvB_MA: true
    SvB: null
    hist_cuts: ["pass_nSelJets_gt6", "fail_nSelJets_le6"]
    top_reconstruction: fast
    plot_ttbar_with_weights: true

plot_config: "coffea4bees/plots/metadata/plotsAll_ttHbb.yml"
known_counts: "coffea4bees/analysis/tests/known_Counts_ttHbb.yml"
cern_user: "algomez"
cern_path: "www/HH4b/Plots/"
dataset:
  - "ttHbb"
year_eras:
  UL18:
    - "A"
    - "B"
    - "C"
    - "D"


convert_hist_to_json:
  histos: 
    - "SvB_MA.ps_ttHbb"
    - "SvB_MA.ps"
combine_outdir: "datacards/"
make_combine_inputs:
  stat_only: ""
  bkgsyst: "coffea4bees/stats_analysis/files/HIG-24-010/hh/hists_closure_3bDvTMix4bDvT_SvB_MA_ps_hh_rebin1.pkl"
channels:
  ttHbb:
    signallabel: "ttHbb"
    othersignal: ""
    variable: "SvB_MA.ps"
    signal: "ttHbb"
    closure_subdir: "hh"
    region: "sum"
    cut: "sum"
  ttHbb_pass:
    signallabel: "ttHbb"
    othersignal: ""
    variable: "SvB_MA.ps"
    signal: "ttHbb"
    closure_subdir: "hh"
    region: "sum"
    cut: "pass_nSelJets_gt6"

combine_flags: "--three_tag threeTag --four_tag fourTag --region sum --blind"
likelihood_scan_points: 20
likelihood_scan_r_min: -10
likelihood_scan_r_max: 10