email: ""
label: "run3_SvB_c6mvd"
# label: "run3_nominal"
output_path: "output/run3_SvB_c6mvd/"
# output_path: "output/run3_nominal/"
analysis_config:
  processor: "coffea4bees/analysis/processors/processor_HH4b.py"
  dataset_location: "coffea4bees/metadata/datasets/"
  friend_file: "coffea4bees/metadata/friends/friends_HH4b.yml"
  weights_file: "coffea4bees/metadata/weights/weights_HH4b.yml"
  runner:
    workers: 4
    worker_memory: 8GB
    dashboard_address: 0
  config:
    blind: false
    apply_FvT: false
    apply_trigWeight: true
    apply_btagSF: true
    apply_boosted_veto: false
    run_SvB: true
    top_reconstruction: fast
    fourTag_use_tight: true
    plot_ttbar_with_weights: false

known_counts: "coffea4bees/analysis/tests/known_Counts_Run3.yml"
plot_config: "coffea4bees/plots/metadata/plotsAll_ttbarWeights.yml"
combine_flags: "--blind"

dataset:
  - "GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00"
  - "TTTo2L2Nu"
  - "TTToSemiLeptonic"
  - "TTToHadronic"

year_eras:
  2022_preEE:
    - "B"
    - "C"
    - "D"
  # 2022_EE:
  #   - "E"
  #   - "F"
  #   - "G"
  # 2023_preBPix:
  #   - "C01"
  #   - "C02"
  #   - "C11"
  #   - "C12"
  #   - "C3"
  #   - "C4"
  # 2023_BPix:
  #   - "D1"
  #   - "D2"

combine_outdir: "datacards/HH4b"
make_combine_inputs:
  stat_only: "--stat_only"
channels:
  HH4b_C2:
    signallabel: "ggHH_kl_1_kt_1_13p0TeV_hbbhbb"
    othersignal: ""
    # variable: "SvB_MA.ps"
    variable: "SvB_c6mvd_C2.ps"
    signal: "GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00"
    closure_subdir: "hh"
  HH4b_C5:
    signallabel: "ggHH_kl_1_kt_1_13p0TeV_hbbhbb"
    othersignal: ""
    variable: "SvB_c6mvd_C5.ps"
    signal: "GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00"
    closure_subdir: "hh"
  HH4b_C5b:
    signallabel: "ggHH_kl_1_kt_1_13p0TeV_hbbhbb"
    othersignal: ""
    variable: "SvB_c6mvd_C5b.ps"
    signal: "GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00"
    closure_subdir: "hh"
  HH4b_C6:
    signallabel: "ggHH_kl_1_kt_1_13p0TeV_hbbhbb"
    othersignal: ""
    variable: "SvB_c6mvd_C6.ps"
    signal: "GluGlutoHHto4B_kl-1p00_kt-1p00_c2-0p00"
    closure_subdir: "hh"
metadata_template: "coffea4bees/stats_analysis/metadata/HH4b_run3.yml"

