eos_base: "root://eoscms.cern.ch//eos/cms/store/group/phys_higgs/ttHbb/mmarcheg/4b/2024_v2/ttHbb_stitched"
plot_base: "root://eosuser.cern.ch//eos/user/m/mmarcheg/www/ttHbb/Plots"

classifier_config_paths: coffea4bees
wfs_base: coffea4bees/classifier/config/workflows/ttHbb_stitched/FvT
label: FvT_ttHbb_stitched
output_dir: output/{label}/

plot_inputs: true
plot_weights: true
evaluate: true

model: "{eos_base}/classifier/{label}"
friend: "{eos_base}/friend/{label}"
train_template: "model: {eos_base}/classifier/{label}"
eval_template: "model: {eos_base}/classifier/{label}, FvT: {eos_base}/friend/{label}"
metadata: "coffea4bees/metadata/datasets/classifier_inputs_ttHbb_stitched.json@@HCR_input"
