main:
  module: train # run training task
  option:
    - --max-loaders 2 # use 2 workers to load dataset
    - --max-trainers 3 # use 3 workers to train

dataset:
  - module: HCR.FvT.TrainBaseline # use the baseline dataset for FvT training
    option:
      - --metadata coffea4bees/metadata/datasets/archive/Run2_2024_v2/
      - --max-workers 20 # use 20 workers to load ROOT files
      - --data-source detector # only use data (not mixed data or synthetic data)
      - --JCM-weight "" coffea4bees/metadata/weights/JCM/Run2_ttHbb/jetCombinatoricModel_SB_2024_v2.yml@@JCM_weights # set JCM weight
      - --friends "" coffea4bees/metadata/datasets/archive/Run2_2024_v2/classifier_inputs_ttHbb.json@@HCR_input 
model:
  - module: HCR.FvT.baseline.Train # use the baseline model for FvT
    option:
      - --kfolds 3 # use 3-fold
      - --kfold-seed FvT random # setup base seed to be ("FvT", "random")
      - --kfold-seed-offsets 0 # use seed ("FvT", "random", 0)
      - --training FixedStep # setup training schedule
      - epoch: 20 # setup kwargs for FixedStep
        bs_init: 1024 # equivalent to use FixedStep(epoch=20, bs_init=1024)
      - --finetuning FixedStep # setup finetuning schedule
      - epoch: 1
        bs_init: 16384

setting:
  - module: IO # setup output directory
    option:
      - output: "{model}" # will be replaced by the template
