main:
  module: train
  option:
    - --max-loaders 2
    - --max-trainers 3

dataset:
  - module: HCR.FvT.TrainBaseline
    option:
      - --metadata coffea4bees/metadata/datasets/
      - --max-workers 20
      - --data-source detector
      - --JCM-weight "" coffea4bees/metadata/weights/JCM/Run2_ttHbb/jetCombinatoricModel_SB_ttHbb_v3.yml@@JCM_weights
      - --friends "" coffea4bees/metadata/datasets/classifier_inputs_ttHbb_v3.json@@HCR_input
model:
  - module: HCR.FvT.baseline.Train
    option:
      - --kfolds 3
      - --kfold-seed FvT random
      - --kfold-seed-offsets 0
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FixedStep
      - epoch: 1
        bs_init: 16384

setting:
  - module: IO
    option:
      - output: "{model}"
