# template:
# - model: path to model
# - MvD: path to friend tree

main:
  module: evaluate
  option:
    - --max-evaluators 3

dataset:
  - module: HCR.MvD.Eval
    option:
      - --metadata coffea4bees/metadata/datasets_HH4b_Run3/archive/datasets_HH4b_Run3_2025_Run3_skims
      - --max-workers 8
      - --data-source detector
      - --friends "" coffea4bees/metadata/datasets_HH4b_Run3/classifier_inputs_MvD_Run3.json@@HCR_input

model:
  - module: HCR.MvD.baseline.Eval
    option:
      - --models
      - Final
      - "{model}/result.json"

analysis:
  - module: kfold.Merge
    option:
      - --name MvD
      - --step 100000
      - --workers 5
      - --clean

setting:
  - module: IO
    option:
      - output: "{MvD}"
  - module: ml.DataLoader
    option:
      - num_workers: 8
