# template:
# - model: path to model
# - SvB: path to friend tree

main:
  module: evaluate
  option:
    - --max-evaluators 1
    - --device cuda cpu # use GPU if available, fall back to CPU

model:
  - module: HCR.SvB.ggF.baseline.Eval
    option:
      - --models
      - Final
      - "{model}/result.json"

dataset:
  - module: HCR.SvB_lowpt.Eval
    option:
      - --metadata coffea4bees/metadata/datasets/
      - --max-workers 8
      - --friends "" coffea4bees/metadata/datasets/classifier_inputs_lowpt_wlowptJCM.json@@HCR_input_lowpt

analysis:
  - module: kfold.Merge
    option:
      - --name SvB
      - --step 100000
      - --workers 5
      - --clean

setting:
  - module: IO
    option:
      - output: "{SvB}"
  - module: ml.DataLoader
    option:
      - num_workers: 8
