# template:
# - model: path to model
# - FvT: path to FvT friend tree

main:
  module: train
  option:
    - --max-loaders 2
    - --max-trainers 3

model:
  - module: HCR.SvB.ggF.baseline.Train
    option:
      - --roc-signal-by-category # calculate ROC by category
      - --kfold-seed SvB random
      - --kfold-seed-offsets 0
      - --architecture
      - n_features: 30
      - --training FixedStep
      - epoch: 20
        bs_init: 1024
      - --finetuning FinetuneStep
      - epoch: 1
        bs_init: 16384

dataset:
  - module: HCR.SvB_lowpt.Background # load background dataset (lowpt version)
    option:
      - --metadata coffea4bees/metadata/datasets_HH4b_Run2/2024_v2/
      - --norm 3
      - --JCM-weight "" coffea4bees/analysis/weights/JCM/Run2_lowpt_v1/jetCombinatoricModel_SB_2024_v2.yml@@JCM_weights
      - --friends "" coffea4bees/metadata/datasets_HH4b_Run2/2024_v2/classifier_inputs_lowpt_wlowptJCM.json@@HCR_input_lowpt
      - --friends label:data {FvT}/result.json@@analysis.0.merged # setup the path to FvT friend tree

  - module: HCR.SvB_lowpt.Signal # load signal dataset (lowpt version)
    option:
      - --metadata coffea4bees/metadata/datasets_HH4b_Run2/2024_v2/
      - --friends "" coffea4bees/metadata/datasets_HH4b_Run2/2024_v2/classifier_inputs_lowpt_wlowptJCM.json@@HCR_input_lowpt

setting:
  - module: IO
    option:
      - output: "{model}"
